service: bicycleforthemind
image: colorfulfool/bicycleforthemind

servers:
  web:
    - 64.226.110.61

proxy:
  ssl: true
  host: bicycle.forthemind.co.uk
  app_port: 8000

registry:
  username: colorfulfool
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

volumes:
  - "app_data:/app/data"
  - "app_media:/app/media"

asset_path: /app/staticfiles
